export const BasicReducerConstants={
    OPEN_SIDEBAR:'OPEN_SIDEBAR',
    CLOSE_SIDEBAR:'CLOSE_SIDEBAR'
}

export const AuthConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',

    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',

    SIGNUP_REQUEST:'SIGNUP_REQUEST',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILURE:'SIGNUP_FAILURE',
}

export const ExpensesConstants={
    CREATE_EXPENSE_REQUEST:'CREATE_EXPENSE_REQUEST',
    CREATE_EXPENSE_SUCCESS:'CREATE_EXPENSE_SUCCESS',
    CREATE_EXPENSE_FAILURE:'CREATE_EXPENSE_FAILURE',

    EDIT_EXPENSE_REQUEST:'EDIT_EXPENSE_REQUEST',
    EDIT_EXPENSE_SUCCESS:'EDIT_EXPENSE_SUCCESS',
    EDIT_EXPENSE_FAILURE:'EDIT_EXPENSE_FAILURE',

    GET_EXPENSES_REQUEST:'GET_EXPENSES_REQUEST',
    GET_EXPENSES_FAILURE:'GET_EXPENSES_FAILURE',
    GET_EXPENSES_SUCCESS:'GET_EXPENSES_SUCCESS'
}

export const UserConstants={
    EDIT_REQUEST:'EDIT_REQUEST',
    EDIT_SUCCESS:'EDIT_SUCCESS',
    EDIT_FAILURE:'EDIT_FAILURE'
}