export const BasicReducerConstants={
    OPEN_SIDEBAR:'OPEN_SIDEBAR',
    CLOSE_SIDEBAR:'CLOSE_SIDEBAR'
}

export const AuthConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE'
}

export const ExpensesConstants={
    CREATE_EXPENSE_REQUEST:'CREATE_EXPENSE_REQUEST',
    CREATE_EXPENSE_SUCCESS:'CREATE_EXPENSE_SUCCESS',
    CREATE_EXPENSE_FAILURE:'CREATE_EXPENSE_FAILURE',

    EDIT_EXPENSE_REQUEST:'EDIT_EXPENSE_REQUEST',
    EDIT_EXPENSE_SUCCESS:'EDIT_EXPENSE_SUCCESS',
    EDIT_EXPENSE_FAILURE:'EDIT_EXPENSE_FAILURE'
}